baseurl: "https://sohailjannessari.github.io/"
languageCode: "en-us"
title: "ّInterregnum"
theme: "hugo-xmag"
googleAnalytics: ""
disqusShortname: "sohailjannessari"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: "↩"
hasCJKLanguage: false
enableEmoji: true
paginate: 6

permalinks:
  post: "/post/:year-:month-:day/:slug/"

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Categories
      url: /categories/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4
    - name: Subscribe
      url: /index.xml

params:
  description: "Sohail Jannessari's personal website"
  footer: "Theme: &copy; [Yihui Xie](https://yihui.org) 2017 - 2020 | [Github](https://github.com/yihui) | [Twitter](https://twitter.com/xieyihui)"
  github_edit: "https://github.com/yihui/hugo-xmag/edit/master/exampleSite/content/"
  summary_length: 300
  text:
    back: "&larr; Home"
    truncated: "&hellip;"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
